### ISSUE TITLE
TypeError: Invalid value used as weak map key

### ISSUE THREAD

**Issue by jperelli** [sindresorhus/map-obj#9]
Sorry, I opened an issue in your oher repo, not sure where I should open this issue

```
TypeError: Invalid value used as weak map key
    at WeakMap.set (native)
    at mapObj (/home/jperelli/celerative/wysh/WYSHAPI/node_modules/map-obj/index.js:23:7)
    at module.exports (/home/jperelli/celerative/wysh/WYSHAPI/node_modules/camelcase-keys/index.js:16:9)
```

What could be causing this error?

**Comment by sindresorhus** [comment]
> Sorry, I opened an issue in your oher repo, not sure where I should open this issue

Don't do that. Especially not without cross-linking between them.
